### ISSUE TITLE
Allow Enable/ Disable extension

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-vs-code#29]
**What should we improve?**
I need the ability to quickly enable / disable Redocly extension. Disable extension from the extensions menu requires VSC to reload and this is not an ideal workflow. 

Here's an idea taken from Live Server extension, one click action
![image](https://user-images.githubusercontent.com/32110157/163201819-5ef5c055-8d52-45b7-868a-f38bf118c735.png)

**Comment by lornajane** [comment]
We discussed the request to add enable/disable features. VSCode now has the ability to enable/disable on a per-workspace basis, so we recommend that users use that feature to achieve this and I'm closing the issue.
