### ISSUE TITLE
synchronize VSC extension with openapi core package releases

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-vs-code#31]
It's my understanding the extension is using openapi core.  VSC is reporting the extension was last updated on March 24, 2022 but there has been at least 5 newer releases on the openapi core package at time of writing. Is the VSC extension in sync with the other package?  I've also noticed and created an issue on the redoc repo to synchronize the demo-bundle.js. @AlexVarchuk has been responding there. 
https://github.com/Redocly/redoc/issues/1896

**Comment by jeremyfiel** [comment]
Please update the VS Code extension in-sync with the openapi-core package releases.. We are missing quite a few changes to the linting behavior of the extension.  Any chance you can use release tags to track the change history?   

as of today, Jan 25, 2023 I'm seeing the following stats. 
```
More Info
Published 8/13/2021, 09:29:18
Last released 12/7/2022, 13:04:49
Last updated 12/7/2022, 22:02:49
Identifier redocly.openapi-vs-code
```

**Comment by jeremyfiel** [comment]
cc @lornajane   VSC extension doesn't have the 1.0 stable release yet

**Comment by tatomyr** [comment]
@jeremyfiel hi, thanks for pointing this out! That's because the `@redocly/openapi-core` package has had no changes since then (only the version updated to be on par with Redocly CLI). We're going to update it as soon as we release the next Redocly CLI version with actual changes.

**Comment by tatomyr** [comment]
I'm closing this issue since this task couldn't be automated for now. There is additional logic in the VSC extension that might be required to update alongside updating the openapi core package. The only way is to manually update the extension after releasing a new version of the openapi core with actual changes.
