### ISSUE TITLE
entire yaml marked with problem "should have `security` defined"

### ISSUE THREAD

**Issue by jabielecki** [Redocly/redocly-vs-code#40]
**What happened?**

I've got a problem "Every API should have security defined on the root level or for each operation" after loading a typical example found on the web (e.g. petstore.yaml). So far so good, because the yaml in fact does have this exact characteristic.

But the attributes of such finding are broken:

- it's a problem (not a warning) underlined in red in VS Code editor
- the *entire* contents of the yaml file is underlined
  - The underline is visually very striking.
  - It's overshadowing any other problem or warning. To be able to observe any other problem/warning I need to add the `security` field to every single operation.

**What should have happened instead?**

- I should see a warning (neither OAS3 or OAS3.1 strictly require `security` field) unerlined in yellow
- Just a relevant part of the yaml file underlined (for example just an operation "get" or "post" alone?)
- These operations that happen to have `security` field should not be underlined.

**Minimal reproducible OpenAPI snippet**

```yaml
openapi: "3.0.0"
info:
paths:
  /pets:
    get:
      responses:
        "200":
```

**Screenshots**

![Screenshot from 2022-10-25 17-35-17](https://user-images.githubusercontent.com/47531708/197818846-046d9816-2e2d-401b-acde-c106ded4ea9d.png)

**Additional context**

Happens on "3.0.0" and "3.1.0".
Today's version of the plugin from VS Code Marketplace: 2022-10-25.

**Comment by AntonKozachuk** [comment]
Hi @jabielecki,

Thanks for raising your concerns.

We already have a fix for this visual issue to avoid highlighting the whole definition.

It will be reporting only on the specific operations that lack security or the `openapi` field itself. 

The fix will be added to the next release.

As for the warning, we will consider your suggestion but our team has a strong opinion that every API should have security defined. 

Even if the API is truly public without any credentials required, define the empty security section to let people know you didn't forget.

Hope this makes sense.

**Comment by jabielecki** [comment]
Thank you very much for working on it!

For the error level, if it's a well-informed and well-intended departure from OAS3, well, you are the experts here :smile: :+1:
