### ISSUE TITLE
Is there any changes for redocly.yaml configuration?

### ISSUE THREAD

**Issue by AviandraP** [Redocly/redocly-vs-code#41]
![image](https://user-images.githubusercontent.com/111033787/199883232-f5e7453e-6287-41e8-8313-7242230e6459.png)

Today i experience this issue, is there any changes so i can update my configuration file correctly?
Thank you.

**Comment by tatomyr** [comment]
Hi @AviandraPutri-Jubelio, 

Some time ago we changed the `redocly.yaml` syntax. Please take a look at [the docs](https://redocly.com/docs/cli/configuration/). 

We will support the old syntax until the stable release, so you can leave it as it is for the time being. However, if you want to update your configuration file, here is the migration guide:  https://redocly.com/docs/api-registry/guides/migration-guide-config-file/#changed-properties .

**Comment by AviandraP** [comment]
hello, i've changed it into the newest one, but this errors keep showing, do you have any idea why?
![image](https://user-images.githubusercontent.com/111033787/200222468-da6c4de1-7681-40fa-8a1f-c53f672bd6c1.png)

**Comment by roman-sainchuk** [comment]
Hello @AviandraP and thank you for reporting an issue.
Unfortunately, we don't have a migration guide from version `< 1.0.0-beta.106` yet. 
Also in the latest versions we don't have `lint` (as well as `styleguide`) field anymore. Please write your `rules` field on top level, e.g.:

```yaml
apis:
  main@v1:
    root: ./openapi.yaml
rules:
  example-rule-name: error
features.openapi:
  ...
```

For `features.openapi` please use [this schema](https://redocly.com/docs/api-reference-docs/configuration/theming/#featuresopenapitheme-schema).

**Comment by roman-sainchuk** [comment]
Hello @AviandraP!
Have the last comment solved your issue?
May we close it?

**Comment by AviandraP** [comment]
Sorry that I forget to tell you, yes i've solved my issue, thank you so much!
