### ISSUE TITLE
Why is there no root directory support in $ref in paths?

### ISSUE THREAD

**Issue by junsred** [Redocly/redocly-vs-code#43]
https://github.com/Redocly/openapi-starter/tree/main/openapi/paths#drawbacks-2

![image](https://user-images.githubusercontent.com/63877982/202248510-2381d33a-d879-46a5-b4a8-ad67ebfe78ad.png)

it is possible to use this way
`$ref: '#/definitions/components/schemas/Error.yaml'` 
but extension shows error even though in preview it works

**Comment by tatomyr** [comment]
Closing this as not active.
