### ISSUE TITLE
Multiline text is inlined after saving/formatting

### ISSUE THREAD

**Issue by redben** [Redocly/redocly-vs-code#53]
**What happened?**

Formatting is changed after saving

*A clear and concise description of your issue.*

The text before saving
![image](https://github.com/Redocly/redocly-vs-code/assets/200361/b94dab7d-9045-402d-921c-aa645607cffa)

The text after saving
![image](https://github.com/Redocly/redocly-vs-code/assets/200361/768fcb2e-3768-4a96-ac87-8273bd3d4cef)

**What should have happened instead?**

*A clear and concise description of the behavior you expected to happen.*

Text formating should not have changed

**Minimal reproducible OpenAPI snippet**

*If possible, include a short example of your OpenAPI definition that we can use to simulate the problem.*

```yaml
openapi: 3.1.0
tags:
  - name: Example
    description: |
      Lorem Ipsum is simply dummy text of the
      printing and typesetting industry. 
      
      Lorem Ipsum has been the industry's standard 
      dummy text ever since the 1500s, 
      when an unknown printer took a galley of type 
      and scrambled it to make a type specimen book. 
```

**Screenshots**

*If applicable, add screenshots to help explain your problem.*

See above

**Additional context**

*Add any other information about the problem here, like: the extension version number; OpenAPI version you're using in your definition; your operating system.*

**Comment by tatomyr** [comment]
Hi @redben! Please provide more details on how you reproduce the issue. Saving keeps the formatting the same for me. Do you use another extension or additional settings in your editor?

**Comment by redben** [comment]
@tatomyr sorry for the late reply.
So if it works for you there might be something wrong with my VS Code setup.
I will close this until I gather more information.

Thanks!
