### ISSUE TITLE
Disable config init prompt for empty projects

### ISSUE THREAD

**Issue by maslennikov** [Redocly/redocly-vs-code#55]
**What happened?**

Every time I open an unrelated project not having a redocly config file (for example, a repo with c++ microcontroller code), extension asks if I want to initialize a config file.

**What should have happened instead?**

I would like to be able to disable this behavior in settings

**Comment by lornajane** [comment]
One suggestion we had when discussion this issue is to prompt for this configuration file when someone opens an openapi file (root file) without the config in the project.
