### ISSUE TITLE
Highlighting error on OpenApi Version

### ISSUE THREAD

**Issue by speedyT0RT0ISE** [Redocly/redocly-vs-code#56]
**What happened?**
Error showing up with OpenAPI version
openapi: 3.0.1

`String does not match the pattern of "^3\.1\.\d+(-.+)?$".yaml-schema: openapi.json
`
**What should have happened instead?**
Should accept the version of 3.0.1

**Minimal reproducible OpenAPI snippet**
openapi: 3.0.1

*If possible, include a short example of your OpenAPI definition that we can use to simulate the problem.*

**Screenshots**

*If applicable, add screenshots to help explain your problem.*
<img width="334" alt="image" src="https://github.com/Redocly/redocly-vs-code/assets/58185129/5ec6b4e0-77d8-4c71-aa36-501dfa2a40b0">

**Additional context**
Hi! Sorry aware this probably isnt a bug, but have trawled through docs and cant find where to set the OpenAPI version - really sorry if this is an obvious configuration error/ fix
*Add any other information about the problem here, like: the extension version number; OpenAPI version you're using in your definition; your operating system.*

**Comment by jeremyfiel** [comment]
I believe this is an error with VS Code and your config.  this is not related to Redocly. 

If you have these or some other similar vs code settings, this is your problem.  The schema for 3.1.0 is colliding with the 3.0.x schema.

```json
 "yaml.schemas": {
    "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.yaml": [
      "/*openapi.yml",
      "/*openapi.yaml"
    ],
    "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.yaml": [
      "/*openapi.yml",
      "/*openapi.yaml"
    ]
}
```

the extension is named in the error output

![image](https://github.com/Redocly/redocly-vs-code/assets/32110157/5df30626-584f-40b3-ae5c-9f4d3eff2d81)


Here's a different example where it shows `Redocly OpenAPI` is recognizing an error

![image](https://github.com/Redocly/redocly-vs-code/assets/32110157/cf9946fa-d301-4724-a824-e3c0adf90c97)

**Comment by speedyT0RT0ISE** [comment]
Hi yes fixed with a VS code update - Sorry!
