### ISSUE TITLE
Extension does not take into account `.redocly.lint-ignore.yaml` file

### ISSUE THREAD

**Issue by vanya909** [Redocly/redocly-vs-code#61]
# Actions:
Add some endpoint to `.redocly.lint-ignore.yaml` file

### Expected behavior
Warning for this endpoint is disappeared in VSCode GUI

### Actual behavior
Warning for this endpoint is still presented in VSCode GUI but it has disappeared in CLI (i.e. when I run `redocly lint` command)

**Comment by jeremyfiel** [comment]
confirmed.. the vs code extension does not resolve an ignore file.

**Comment by adamaltman** [comment]
Maybe the VS Code extension needs to set the config of the ignore file...

https://github.com/Redocly/redocly-cli/blob/918f570203e31dda9c9fe38548ab559119b686b3/packages/core/src/config/config.ts#L117

@tatomyr ?

I also hit this issue when using the extension.

**Comment by tatomyr** [comment]
@adamaltman the extension resolves config correctly (including the ignore file), but the linter isn't taking it into account for some reason. Might be some kind of pointers mismatch due to different environments.

**Comment by RomanHotsiy** [comment]
@tatomyr @adamaltman here is the fix: https://github.com/Redocly/openapi-vs-code/pull/209

cc @lornajane

**Comment by tatomyr** [comment]
Thanks @RomanHotsiy! Will include this into today's release.
