### ISSUE TITLE
Support YAML v1.2 merge

### ISSUE THREAD

**Issue by danicc097** [Redocly/redocly-vs-code#68]
**What happened?**

There is support for `<<` but not `!!merge <<`, leading to

```
Error: bad indentation of a mapping entry <...>
    at u2e (<...>/.vscode-server/extensions/redocly.openapi-vs-code-0.4.8/out/server/src/server.js:118:339)
    at sg (<...>/.vscode-server/extensions/redocly.openapi-vs-code-0.4.8/out/server/src/server.js:247:4997)
```

which prevents further analysis

**Minimal reproducible OpenAPI snippet**

```yaml
x-uuidIDParameterBase: &x-uuidIDParameterBase
  description: UUID identifier
  explode: false
  in: path
  required: true
  schema:
    type: string
    pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
    # https://github.com/deepmap/oapi-codegen/issues/760
    x-go-type: uuid.UUID
    x-go-type-import:
      name: uuid
      path: github.com/google/uuid
  example: 123e4567-e89b-12d3-a456-426614174000
  style: simple
x-uuidParameter: &x-uuidParameter
  !!merge <<: *x-uuidIDParameterBase
  name: id
openapi: 3.0.2
info:
  description:
    "This is a sample server Petstore server. For this sample, you can\
    \ use the api key `special-key` to test the authorization filters."
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: OpenAPI Petstore
  version: 2.0.0
servers:
  - url: http://localhost:8090/v2
tags:
  - description: Everything about your Pets
    name: pet
  - description: Access to Petstore orders
    name: store
  - description: Operations about user
    name: user
paths:
  /pet/ConflictEndpointPet:
    get:
      description: ""
      operationId: ConflictEndpointPet
      responses:
        "200":
          description: Ok
      summary: name clashing test
      tags:
        - pet

```

**Comment by tatomyr** [comment]
I cannot find any references to the `!!merge <<` syntax in the YAML spec. Could you point me to some resources where I can learn more about that?

**Comment by danicc097** [comment]
https://yaml.org/spec/1.2.2/ext/changes/ mentions `The merge << and value = special mapping keys have been removed.`

Some libraries like yq [adhere to it](https://github.com/mikefarah/yq/issues/680#issuecomment-764542837), others accept both forms and some don't recognize the explicit merge tag such as this extension

**Comment by tatomyr** [comment]
I still don't see anything like `!!merge <<` in the specification. I don't believe it makes sense to add something that is not spec-compliant. 
Anyway, I think it's the library we're using for parsing YAML (either *js-yaml* or *yaml-ast-parser*) that produces the error you're getting, so I'm closing the issue. 

Let me know if I've missed something.
