### ISSUE TITLE
Extension doesn't honor openapiversion when selecting json.schema

### ISSUE THREAD

**Issue by WalternativE** [Redocly/redocly-vs-code#69]
**What happened?**

Regardless of the version used in the `openapi` attribute the extension always selects a `json.schema` corresponding to the 3.1 version (id https://spec.openapis.org/oas/3.1/schema/2022-10-07).

**What should have happened instead?**

The extension should either honor the selected version or allow users to override the schema version (or location). This should also fix issues users have with being suggested wrong autocomplete options like in #46 (if I am not completely mistaken).

**Minimal reproducible OpenAPI snippet**

```yaml
openapi: 3.0.3
info:
  title: "A Title"
  version: 0.0.1
  license:
    name: "A Name"
    url: www.google.com
servers:
  - url: 127.0.0.1/api
paths:
  /health:
    get:
      operationId: get_application_health
      summary: Indicates whether app is up and healthy.
      tags:
        -  general
      responses:
        "200":
          description: Application is healthy.
        "500":
          description: Application health check is failing.
      security: []
```

**Screenshots**

![Screenshot 2024-09-09 at 17 26 13](https://github.com/user-attachments/assets/82379927-4326-4f3b-9502-032a51db69d4)

**Additional context**

- MacOS 14.6.1
- VSCode 1.93.0
- Redocly OpenAPI v0.4.8
- no proxy, no vpn

**Comment by tatomyr** [comment]
Hi @WalternativE, this error most likely stems from another extension. Otherwise it'd show a message like in the screenshot below:
<img width="494" alt="Screenshot 2024-09-09 at 18 47 34" src="https://github.com/user-attachments/assets/4f97197e-e90a-4450-a15b-fde85cd5d2c3">

**Comment by WalternativE** [comment]
Hi @tatomyr, thank you very much for pointing me into the right direction! It was indeed the YAML extension which caused the problem. I found a workaround for the problem following [the instructions in this GitHub issue](https://github.com/redhat-developer/vscode-yaml/issues/532#issuecomment-2092819034).
